name: Valid PR Title
run-name: Valid PR Title on ${{ github.head_ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  valid-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - id: lint-pr-title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            autorelease: pending

      - id: display-error
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint-pr-title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint-pr-title.outputs.error_message }}
            ```

      # Delete a previous comment when the title is fixed
      - id: remove-error
        if: ${{ steps.lint-pr-title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
